# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class HelloAssoApiV5ModelsEnumsMembershipValidityType(str, Enum):
    """
    Enum which represents the membership validity type
    """

    """
    allowed enum values
    """
    MOVINGYEAR = 'MovingYear'
    CUSTOM = 'Custom'
    ILLIMITED = 'Illimited'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of HelloAssoApiV5ModelsEnumsMembershipValidityType from a JSON string"""
        return cls(json.loads(json_str))


