# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class HelloAssoApiV5ModelsEnumsPaymentState(str, Enum):
    """
    HelloAssoApiV5ModelsEnumsPaymentState
    """

    """
    allowed enum values
    """
    PENDING = 'Pending'
    AUTHORIZED = 'Authorized'
    REFUSED = 'Refused'
    UNKNOWN = 'Unknown'
    REGISTERED = 'Registered'
    ERROR = 'Error'
    REFUNDED = 'Refunded'
    REFUNDING = 'Refunding'
    WAITING = 'Waiting'
    CANCELED = 'Canceled'
    CONTESTED = 'Contested'
    WAITINGBANKVALIDATION = 'WaitingBankValidation'
    WAITINGBANKWITHDRAW = 'WaitingBankWithdraw'
    ABANDONED = 'Abandoned'
    WAITINGAUTHENTICATION = 'WaitingAuthentication'
    AUTHORIZEDPREPROD = 'AuthorizedPreprod'
    CORRECTED = 'Corrected'
    DELETED = 'Deleted'
    INCONSISTENT = 'Inconsistent'
    NODONATION = 'NoDonation'
    INIT = 'Init'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of HelloAssoApiV5ModelsEnumsPaymentState from a JSON string"""
        return cls(json.loads(json_str))


