# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class HelloAssoApiV5CommonModelsEnumsTierType(str, Enum):
    """
    HelloAssoApiV5CommonModelsEnumsTierType
    """

    """
    allowed enum values
    """
    DONATION = 'Donation'
    PAYMENT = 'Payment'
    REGISTRATION = 'Registration'
    MEMBERSHIP = 'Membership'
    MONTHLYDONATION = 'MonthlyDonation'
    MONTHLYPAYMENT = 'MonthlyPayment'
    OFFLINEDONATION = 'OfflineDonation'
    CONTRIBUTION = 'Contribution'
    BONUS = 'Bonus'
    PRODUCT = 'Product'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of HelloAssoApiV5CommonModelsEnumsTierType from a JSON string"""
        return cls(json.loads(json_str))


