# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_common_models_statistics_payer import HelloAssoApiV5CommonModelsStatisticsPayer

class TestHelloAssoApiV5CommonModelsStatisticsPayer(unittest.TestCase):
    """HelloAssoApiV5CommonModelsStatisticsPayer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5CommonModelsStatisticsPayer:
        """Test HelloAssoApiV5CommonModelsStatisticsPayer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5CommonModelsStatisticsPayer`
        """
        model = HelloAssoApiV5CommonModelsStatisticsPayer()
        if include_optional:
            return HelloAssoApiV5CommonModelsStatisticsPayer(
                email = '',
                address = '',
                city = '',
                zip_code = '',
                country = '',
                company = '',
                date_of_birth = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                first_name = '',
                last_name = ''
            )
        else:
            return HelloAssoApiV5CommonModelsStatisticsPayer(
        )
        """

    def testHelloAssoApiV5CommonModelsStatisticsPayer(self):
        """Test HelloAssoApiV5CommonModelsStatisticsPayer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
