# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_common_models_forms_form_quick_create_model import HelloAssoApiV5CommonModelsFormsFormQuickCreateModel

class TestHelloAssoApiV5CommonModelsFormsFormQuickCreateModel(unittest.TestCase):
    """HelloAssoApiV5CommonModelsFormsFormQuickCreateModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5CommonModelsFormsFormQuickCreateModel:
        """Test HelloAssoApiV5CommonModelsFormsFormQuickCreateModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5CommonModelsFormsFormQuickCreateModel`
        """
        model = HelloAssoApiV5CommonModelsFormsFormQuickCreateModel()
        if include_optional:
            return HelloAssoApiV5CommonModelsFormsFormQuickCreateModel(
                form_slug = '',
                organization_slug = '',
                public_url = ''
            )
        else:
            return HelloAssoApiV5CommonModelsFormsFormQuickCreateModel(
        )
        """

    def testHelloAssoApiV5CommonModelsFormsFormQuickCreateModel(self):
        """Test HelloAssoApiV5CommonModelsFormsFormQuickCreateModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
