# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_models_statistics_share_payment import HelloAssoApiV5ModelsStatisticsSharePayment

class TestHelloAssoApiV5ModelsStatisticsSharePayment(unittest.TestCase):
    """HelloAssoApiV5ModelsStatisticsSharePayment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5ModelsStatisticsSharePayment:
        """Test HelloAssoApiV5ModelsStatisticsSharePayment
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5ModelsStatisticsSharePayment`
        """
        model = HelloAssoApiV5ModelsStatisticsSharePayment()
        if include_optional:
            return HelloAssoApiV5ModelsStatisticsSharePayment(
                id = 56,
                share_amount = 56
            )
        else:
            return HelloAssoApiV5ModelsStatisticsSharePayment(
        )
        """

    def testHelloAssoApiV5ModelsStatisticsSharePayment(self):
        """Test HelloAssoApiV5ModelsStatisticsSharePayment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
