# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_models_organizations_organization_public_configuration_key import HelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationKey

class TestHelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationKey(unittest.TestCase):
    """HelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationKey(self):
        """Test HelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationKey"""
        # inst = HelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationKey()

if __name__ == '__main__':
    unittest.main()
