# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_models_enums_operation_state import HelloAssoApiV5ModelsEnumsOperationState

class TestHelloAssoApiV5ModelsEnumsOperationState(unittest.TestCase):
    """HelloAssoApiV5ModelsEnumsOperationState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHelloAssoApiV5ModelsEnumsOperationState(self):
        """Test HelloAssoApiV5ModelsEnumsOperationState"""
        # inst = HelloAssoApiV5ModelsEnumsOperationState()

if __name__ == '__main__':
    unittest.main()
