# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_common_models_accounts_company_legal_status_model import HelloAssoApiV5CommonModelsAccountsCompanyLegalStatusModel

class TestHelloAssoApiV5CommonModelsAccountsCompanyLegalStatusModel(unittest.TestCase):
    """HelloAssoApiV5CommonModelsAccountsCompanyLegalStatusModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5CommonModelsAccountsCompanyLegalStatusModel:
        """Test HelloAssoApiV5CommonModelsAccountsCompanyLegalStatusModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5CommonModelsAccountsCompanyLegalStatusModel`
        """
        model = HelloAssoApiV5CommonModelsAccountsCompanyLegalStatusModel()
        if include_optional:
            return HelloAssoApiV5CommonModelsAccountsCompanyLegalStatusModel(
                id = 56,
                label = ''
            )
        else:
            return HelloAssoApiV5CommonModelsAccountsCompanyLegalStatusModel(
        )
        """

    def testHelloAssoApiV5CommonModelsAccountsCompanyLegalStatusModel(self):
        """Test HelloAssoApiV5CommonModelsAccountsCompanyLegalStatusModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
