# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_models_directory_synchronizable_form_model import HelloAssoApiV5ModelsDirectorySynchronizableFormModel

class TestHelloAssoApiV5ModelsDirectorySynchronizableFormModel(unittest.TestCase):
    """HelloAssoApiV5ModelsDirectorySynchronizableFormModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5ModelsDirectorySynchronizableFormModel:
        """Test HelloAssoApiV5ModelsDirectorySynchronizableFormModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5ModelsDirectorySynchronizableFormModel`
        """
        model = HelloAssoApiV5ModelsDirectorySynchronizableFormModel()
        if include_optional:
            return HelloAssoApiV5ModelsDirectorySynchronizableFormModel(
                action = 'Insert',
                record = helloasso_python.models.hello_asso/api/v5/models/forms/form_basic_model.HelloAsso.Api.V5.Models.Forms.FormBasicModel(
                    form_slug = '', 
                    form_type = 'CrowdFunding', 
                    url = '', 
                    organization_slug = '', )
            )
        else:
            return HelloAssoApiV5ModelsDirectorySynchronizableFormModel(
        )
        """

    def testHelloAssoApiV5ModelsDirectorySynchronizableFormModel(self):
        """Test HelloAssoApiV5ModelsDirectorySynchronizableFormModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
