# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_models_forms_term_model import HelloAssoApiV5ModelsFormsTermModel

class TestHelloAssoApiV5ModelsFormsTermModel(unittest.TestCase):
    """HelloAssoApiV5ModelsFormsTermModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5ModelsFormsTermModel:
        """Test HelloAssoApiV5ModelsFormsTermModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5ModelsFormsTermModel`
        """
        model = HelloAssoApiV5ModelsFormsTermModel()
        if include_optional:
            return HelloAssoApiV5ModelsFormsTermModel(
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                amount = 56
            )
        else:
            return HelloAssoApiV5ModelsFormsTermModel(
        )
        """

    def testHelloAssoApiV5ModelsFormsTermModel(self):
        """Test HelloAssoApiV5ModelsFormsTermModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
