# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_models_statistics_payment_item import HelloAssoApiV5ModelsStatisticsPaymentItem

class TestHelloAssoApiV5ModelsStatisticsPaymentItem(unittest.TestCase):
    """HelloAssoApiV5ModelsStatisticsPaymentItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5ModelsStatisticsPaymentItem:
        """Test HelloAssoApiV5ModelsStatisticsPaymentItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5ModelsStatisticsPaymentItem`
        """
        model = HelloAssoApiV5ModelsStatisticsPaymentItem()
        if include_optional:
            return HelloAssoApiV5ModelsStatisticsPaymentItem(
                share_amount = 56,
                share_item_amount = 56,
                share_options_amount = 56,
                id = 56,
                amount = 56,
                type = 'Donation',
                initial_amount = 56,
                state = 'Waiting',
                name = ''
            )
        else:
            return HelloAssoApiV5ModelsStatisticsPaymentItem(
        )
        """

    def testHelloAssoApiV5ModelsStatisticsPaymentItem(self):
        """Test HelloAssoApiV5ModelsStatisticsPaymentItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
