# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_common_models_directory_synchronizable_organization_model import HelloAssoApiV5CommonModelsDirectorySynchronizableOrganizationModel

class TestHelloAssoApiV5CommonModelsDirectorySynchronizableOrganizationModel(unittest.TestCase):
    """HelloAssoApiV5CommonModelsDirectorySynchronizableOrganizationModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5CommonModelsDirectorySynchronizableOrganizationModel:
        """Test HelloAssoApiV5CommonModelsDirectorySynchronizableOrganizationModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5CommonModelsDirectorySynchronizableOrganizationModel`
        """
        model = HelloAssoApiV5CommonModelsDirectorySynchronizableOrganizationModel()
        if include_optional:
            return HelloAssoApiV5CommonModelsDirectorySynchronizableOrganizationModel(
                action = 'Insert',
                record = helloasso_python.models.hello_asso/api/v5/common/models/organization/organization_basic_model.HelloAsso.Api.V5.Common.Models.Organization.OrganizationBasicModel(
                    url = '', 
                    organization_slug = '', )
            )
        else:
            return HelloAssoApiV5CommonModelsDirectorySynchronizableOrganizationModel(
        )
        """

    def testHelloAssoApiV5CommonModelsDirectorySynchronizableOrganizationModel(self):
        """Test HelloAssoApiV5CommonModelsDirectorySynchronizableOrganizationModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
