# coding: utf-8

"""
    HelloAsso API

    HelloAsso Open Api specification

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.hello_asso_api_v5_models_enums_price_category import HelloAssoApiV5ModelsEnumsPriceCategory

class TestHelloAssoApiV5ModelsEnumsPriceCategory(unittest.TestCase):
    """HelloAssoApiV5ModelsEnumsPriceCategory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHelloAssoApiV5ModelsEnumsPriceCategory(self):
        """Test HelloAssoApiV5ModelsEnumsPriceCategory"""
        # inst = HelloAssoApiV5ModelsEnumsPriceCategory()

if __name__ == '__main__':
    unittest.main()
