# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.api.utilisateurs_api import UtilisateursApi


class TestUtilisateursApi(unittest.TestCase):
    """UtilisateursApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UtilisateursApi()

    def tearDown(self) -> None:
        pass

    def test_users_me_organizations_get(self) -> None:
        """Test case for users_me_organizations_get

        Obtenir mes organisations
        """
        pass


if __name__ == '__main__':
    unittest.main()
