# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_models_organization_legal_informations_organization_legal_structures_model import HelloAssoApiV5ModelsOrganizationLegalInformationsOrganizationLegalStructuresModel

class TestHelloAssoApiV5ModelsOrganizationLegalInformationsOrganizationLegalStructuresModel(unittest.TestCase):
    """HelloAssoApiV5ModelsOrganizationLegalInformationsOrganizationLegalStructuresModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5ModelsOrganizationLegalInformationsOrganizationLegalStructuresModel:
        """Test HelloAssoApiV5ModelsOrganizationLegalInformationsOrganizationLegalStructuresModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5ModelsOrganizationLegalInformationsOrganizationLegalStructuresModel`
        """
        model = HelloAssoApiV5ModelsOrganizationLegalInformationsOrganizationLegalStructuresModel()
        if include_optional:
            return HelloAssoApiV5ModelsOrganizationLegalInformationsOrganizationLegalStructuresModel(
                id = 56,
                legal_structure = '',
                agreement = '',
                is_fiscal_receipt_eligible = True
            )
        else:
            return HelloAssoApiV5ModelsOrganizationLegalInformationsOrganizationLegalStructuresModel(
        )
        """

    def testHelloAssoApiV5ModelsOrganizationLegalInformationsOrganizationLegalStructuresModel(self):
        """Test HelloAssoApiV5ModelsOrganizationLegalInformationsOrganizationLegalStructuresModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
