# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_common_models_carts_checkout_payer import HelloAssoApiV5CommonModelsCartsCheckoutPayer

class TestHelloAssoApiV5CommonModelsCartsCheckoutPayer(unittest.TestCase):
    """HelloAssoApiV5CommonModelsCartsCheckoutPayer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5CommonModelsCartsCheckoutPayer:
        """Test HelloAssoApiV5CommonModelsCartsCheckoutPayer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5CommonModelsCartsCheckoutPayer`
        """
        model = HelloAssoApiV5CommonModelsCartsCheckoutPayer()
        if include_optional:
            return HelloAssoApiV5CommonModelsCartsCheckoutPayer(
                first_name = '',
                last_name = '',
                email = '',
                date_of_birth = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                address = '',
                city = '',
                zip_code = '',
                country = '012',
                company_name = ''
            )
        else:
            return HelloAssoApiV5CommonModelsCartsCheckoutPayer(
        )
        """

    def testHelloAssoApiV5CommonModelsCartsCheckoutPayer(self):
        """Test HelloAssoApiV5CommonModelsCartsCheckoutPayer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
