# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_models_organizations_organization_public_configuration_model import HelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationModel

class TestHelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationModel(unittest.TestCase):
    """HelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationModel:
        """Test HelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationModel`
        """
        model = HelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationModel()
        if include_optional:
            return HelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationModel(
                name = 'DonationSepaEnabled',
                value = None
            )
        else:
            return HelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationModel(
        )
        """

    def testHelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationModel(self):
        """Test HelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
