# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_common_models_accounts_clients_api_client_model import HelloAssoApiV5CommonModelsAccountsClientsApiClientModel

class TestHelloAssoApiV5CommonModelsAccountsClientsApiClientModel(unittest.TestCase):
    """HelloAssoApiV5CommonModelsAccountsClientsApiClientModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5CommonModelsAccountsClientsApiClientModel:
        """Test HelloAssoApiV5CommonModelsAccountsClientsApiClientModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5CommonModelsAccountsClientsApiClientModel`
        """
        model = HelloAssoApiV5CommonModelsAccountsClientsApiClientModel()
        if include_optional:
            return HelloAssoApiV5CommonModelsAccountsClientsApiClientModel(
                id = '',
                secret = '',
                partner_name = '',
                privileges = [
                    ''
                    ],
                domain = ''
            )
        else:
            return HelloAssoApiV5CommonModelsAccountsClientsApiClientModel(
        )
        """

    def testHelloAssoApiV5CommonModelsAccountsClientsApiClientModel(self):
        """Test HelloAssoApiV5CommonModelsAccountsClientsApiClientModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
