# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_common_models_enums_payment_frequency_type import HelloAssoApiV5CommonModelsEnumsPaymentFrequencyType

class TestHelloAssoApiV5CommonModelsEnumsPaymentFrequencyType(unittest.TestCase):
    """HelloAssoApiV5CommonModelsEnumsPaymentFrequencyType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHelloAssoApiV5CommonModelsEnumsPaymentFrequencyType(self):
        """Test HelloAssoApiV5CommonModelsEnumsPaymentFrequencyType"""
        # inst = HelloAssoApiV5CommonModelsEnumsPaymentFrequencyType()

if __name__ == '__main__':
    unittest.main()
