# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_common_models_payment_cashout_export_cashout_export_payment_status import HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportPaymentStatus

class TestHelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportPaymentStatus(unittest.TestCase):
    """HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportPaymentStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportPaymentStatus(self):
        """Test HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportPaymentStatus"""
        # inst = HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportPaymentStatus()

if __name__ == '__main__':
    unittest.main()
