# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_models_enums_membership_validity_type import HelloAssoApiV5ModelsEnumsMembershipValidityType

class TestHelloAssoApiV5ModelsEnumsMembershipValidityType(unittest.TestCase):
    """HelloAssoApiV5ModelsEnumsMembershipValidityType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHelloAssoApiV5ModelsEnumsMembershipValidityType(self):
        """Test HelloAssoApiV5ModelsEnumsMembershipValidityType"""
        # inst = HelloAssoApiV5ModelsEnumsMembershipValidityType()

if __name__ == '__main__':
    unittest.main()
