# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.api.checkout_api import CheckoutApi


class TestCheckoutApi(unittest.TestCase):
    """CheckoutApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CheckoutApi()

    def tearDown(self) -> None:
        pass

    def test_organizations_organization_slug_checkout_intents_checkout_intent_id_get(self) -> None:
        """Test case for organizations_organization_slug_checkout_intents_checkout_intent_id_get

        Récupérer une intention de paiement
        """
        pass

    def test_organizations_organization_slug_checkout_intents_post(self) -> None:
        """Test case for organizations_organization_slug_checkout_intents_post

        Initialisation d'un Checkout
        """
        pass


if __name__ == '__main__':
    unittest.main()
