# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_common_models_organizations_organization_light_model import HelloAssoApiV5CommonModelsOrganizationsOrganizationLightModel

class TestHelloAssoApiV5CommonModelsOrganizationsOrganizationLightModel(unittest.TestCase):
    """HelloAssoApiV5CommonModelsOrganizationsOrganizationLightModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5CommonModelsOrganizationsOrganizationLightModel:
        """Test HelloAssoApiV5CommonModelsOrganizationsOrganizationLightModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5CommonModelsOrganizationsOrganizationLightModel`
        """
        model = HelloAssoApiV5CommonModelsOrganizationsOrganizationLightModel()
        if include_optional:
            return HelloAssoApiV5CommonModelsOrganizationsOrganizationLightModel(
                logo = '',
                name = '',
                role = 'OrganizationAdmin',
                city = '',
                zip_code = '',
                description = '',
                update_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                category_jo_id = 56,
                url = '',
                organization_slug = ''
            )
        else:
            return HelloAssoApiV5CommonModelsOrganizationsOrganizationLightModel(
        )
        """

    def testHelloAssoApiV5CommonModelsOrganizationsOrganizationLightModel(self):
        """Test HelloAssoApiV5CommonModelsOrganizationsOrganizationLightModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
