# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.api.organisation_api import OrganisationApi


class TestOrganisationApi(unittest.TestCase):
    """OrganisationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrganisationApi()

    def tearDown(self) -> None:
        pass

    def test_organizations_legal_informations_legal_structures_get(self) -> None:
        """Test case for organizations_legal_informations_legal_structures_get

        Obtenir la structure juridique d'une organisation visible.
        """
        pass

    def test_organizations_legal_informations_organization_slug_configuration_get(self) -> None:
        """Test case for organizations_legal_informations_organization_slug_configuration_get

        Obtenir la configuration des informations juridiques de l'organisation.
        """
        pass

    def test_organizations_legal_informations_organization_slug_configuration_put(self) -> None:
        """Test case for organizations_legal_informations_organization_slug_configuration_put

        Mettre à jour la configuration des informations juridiques de l'organisation.
        """
        pass

    def test_organizations_legal_informations_tax_information_texts_get(self) -> None:
        """Test case for organizations_legal_informations_tax_information_texts_get

        Obtenir les textes d'information fiscale de l'organisation.
        """
        pass

    def test_organizations_organization_slug_get(self) -> None:
        """Test case for organizations_organization_slug_get

        Obtenir le détail d'une organisation
        """
        pass


if __name__ == '__main__':
    unittest.main()
