# coding: utf-8

"""
    HelloAsso API

    HelloAsso Open Api specification

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.hello_asso_api_v5_models_enums_payment_state import HelloAssoApiV5ModelsEnumsPaymentState

class TestHelloAssoApiV5ModelsEnumsPaymentState(unittest.TestCase):
    """HelloAssoApiV5ModelsEnumsPaymentState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHelloAssoApiV5ModelsEnumsPaymentState(self):
        """Test HelloAssoApiV5ModelsEnumsPaymentState"""
        # inst = HelloAssoApiV5ModelsEnumsPaymentState()

if __name__ == '__main__':
    unittest.main()
