# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_models_statistics_user import HelloAssoApiV5ModelsStatisticsUser

class TestHelloAssoApiV5ModelsStatisticsUser(unittest.TestCase):
    """HelloAssoApiV5ModelsStatisticsUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5ModelsStatisticsUser:
        """Test HelloAssoApiV5ModelsStatisticsUser
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5ModelsStatisticsUser`
        """
        model = HelloAssoApiV5ModelsStatisticsUser()
        if include_optional:
            return HelloAssoApiV5ModelsStatisticsUser(
                first_name = '',
                last_name = ''
            )
        else:
            return HelloAssoApiV5ModelsStatisticsUser(
        )
        """

    def testHelloAssoApiV5ModelsStatisticsUser(self):
        """Test HelloAssoApiV5ModelsStatisticsUser"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
