# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_common_models_carts_init_checkout_response import HelloAssoApiV5CommonModelsCartsInitCheckoutResponse

class TestHelloAssoApiV5CommonModelsCartsInitCheckoutResponse(unittest.TestCase):
    """HelloAssoApiV5CommonModelsCartsInitCheckoutResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5CommonModelsCartsInitCheckoutResponse:
        """Test HelloAssoApiV5CommonModelsCartsInitCheckoutResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5CommonModelsCartsInitCheckoutResponse`
        """
        model = HelloAssoApiV5CommonModelsCartsInitCheckoutResponse()
        if include_optional:
            return HelloAssoApiV5CommonModelsCartsInitCheckoutResponse(
                id = 56,
                redirect_url = ''
            )
        else:
            return HelloAssoApiV5CommonModelsCartsInitCheckoutResponse(
        )
        """

    def testHelloAssoApiV5CommonModelsCartsInitCheckoutResponse(self):
        """Test HelloAssoApiV5CommonModelsCartsInitCheckoutResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
