# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_common_models_payment_cashout_export_cashout_export_row_model import HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel

class TestHelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel(unittest.TestCase):
    """HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel:
        """Test HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel`
        """
        model = HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel()
        if include_optional:
            return HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel(
                campaign_type = 'CrowdFunding',
                campaign_name = '',
                operation_type = 'MonthlyDonation',
                credit = 1.337,
                debit = 1.337,
                order_id = 56,
                payment_id = 56,
                payment_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                payment_method = 'None',
                payment_status = 'Paid',
                cash_out_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                cash_out_id = 56,
                designation = '',
                payer_company = '',
                payer_last_name = '',
                payer_first_name = '',
                payer_email = '',
                payer_siren = ''
            )
        else:
            return HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel(
        )
        """

    def testHelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel(self):
        """Test HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportRowModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
