# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_models_forms_tier_light_model import HelloAssoApiV5ModelsFormsTierLightModel

class TestHelloAssoApiV5ModelsFormsTierLightModel(unittest.TestCase):
    """HelloAssoApiV5ModelsFormsTierLightModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5ModelsFormsTierLightModel:
        """Test HelloAssoApiV5ModelsFormsTierLightModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5ModelsFormsTierLightModel`
        """
        model = HelloAssoApiV5ModelsFormsTierLightModel()
        if include_optional:
            return HelloAssoApiV5ModelsFormsTierLightModel(
                label = '',
                price = 56
            )
        else:
            return HelloAssoApiV5ModelsFormsTierLightModel(
        )
        """

    def testHelloAssoApiV5ModelsFormsTierLightModel(self):
        """Test HelloAssoApiV5ModelsFormsTierLightModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
