# coding: utf-8

"""
    HelloAsso API

    HelloAsso Open Api specification

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.hello_asso_api_v5_models_enums_record_action_type import HelloAssoApiV5ModelsEnumsRecordActionType

class TestHelloAssoApiV5ModelsEnumsRecordActionType(unittest.TestCase):
    """HelloAssoApiV5ModelsEnumsRecordActionType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHelloAssoApiV5ModelsEnumsRecordActionType(self):
        """Test HelloAssoApiV5ModelsEnumsRecordActionType"""
        # inst = HelloAssoApiV5ModelsEnumsRecordActionType()

if __name__ == '__main__':
    unittest.main()
