# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_models_payments_cash_in_fiscal_receipt_fiscal_receipt_format_option import HelloAssoModelsPaymentsCashInFiscalReceiptFiscalReceiptFormatOption

class TestHelloAssoModelsPaymentsCashInFiscalReceiptFiscalReceiptFormatOption(unittest.TestCase):
    """HelloAssoModelsPaymentsCashInFiscalReceiptFiscalReceiptFormatOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoModelsPaymentsCashInFiscalReceiptFiscalReceiptFormatOption:
        """Test HelloAssoModelsPaymentsCashInFiscalReceiptFiscalReceiptFormatOption
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoModelsPaymentsCashInFiscalReceiptFiscalReceiptFormatOption`
        """
        model = HelloAssoModelsPaymentsCashInFiscalReceiptFiscalReceiptFormatOption()
        if include_optional:
            return HelloAssoModelsPaymentsCashInFiscalReceiptFiscalReceiptFormatOption(
                var_date = '',
                order = '',
                root = '',
                separator = ''
            )
        else:
            return HelloAssoModelsPaymentsCashInFiscalReceiptFiscalReceiptFormatOption(
        )
        """

    def testHelloAssoModelsPaymentsCashInFiscalReceiptFiscalReceiptFormatOption(self):
        """Test HelloAssoModelsPaymentsCashInFiscalReceiptFiscalReceiptFormatOption"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
