# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_models_account_company_legal_status_model import HelloAssoApiV5ModelsAccountCompanyLegalStatusModel

class TestHelloAssoApiV5ModelsAccountCompanyLegalStatusModel(unittest.TestCase):
    """HelloAssoApiV5ModelsAccountCompanyLegalStatusModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5ModelsAccountCompanyLegalStatusModel:
        """Test HelloAssoApiV5ModelsAccountCompanyLegalStatusModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5ModelsAccountCompanyLegalStatusModel`
        """
        model = HelloAssoApiV5ModelsAccountCompanyLegalStatusModel()
        if include_optional:
            return HelloAssoApiV5ModelsAccountCompanyLegalStatusModel(
                id = 56,
                label = ''
            )
        else:
            return HelloAssoApiV5ModelsAccountCompanyLegalStatusModel(
        )
        """

    def testHelloAssoApiV5ModelsAccountCompanyLegalStatusModel(self):
        """Test HelloAssoApiV5ModelsAccountCompanyLegalStatusModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
