# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.api.values_definitions_api import ValuesDefinitionsApi


class TestValuesDefinitionsApi(unittest.TestCase):
    """ValuesDefinitionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ValuesDefinitionsApi()

    def tearDown(self) -> None:
        pass

    def test_values_form_form_type_types_get(self) -> None:
        """Test case for values_form_form_type_types_get

        Get all activity types for a form type
        """
        pass


if __name__ == '__main__':
    unittest.main()
