# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_models_tags_internal_tag_model import HelloAssoApiV5ModelsTagsInternalTagModel

class TestHelloAssoApiV5ModelsTagsInternalTagModel(unittest.TestCase):
    """HelloAssoApiV5ModelsTagsInternalTagModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5ModelsTagsInternalTagModel:
        """Test HelloAssoApiV5ModelsTagsInternalTagModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5ModelsTagsInternalTagModel`
        """
        model = HelloAssoApiV5ModelsTagsInternalTagModel()
        if include_optional:
            return HelloAssoApiV5ModelsTagsInternalTagModel(
                id = 56,
                name = '',
                form_count = 56,
                organization_count = 56,
                tag_type = 'Explore',
                tag_parent = helloasso_python.models.hello_asso/api/v5/models/tags/internal_tag_model.HelloAsso.Api.V5.Models.Tags.InternalTagModel(
                    id = 56, 
                    name = '', 
                    form_count = 56, 
                    organization_count = 56, 
                    tag_type = 'Explore', 
                    tag_parent = helloasso_python.models.hello_asso/api/v5/models/tags/internal_tag_model.HelloAsso.Api.V5.Models.Tags.InternalTagModel(
                        id = 56, 
                        name = '', 
                        form_count = 56, 
                        organization_count = 56, 
                        amount_collected = 56, ), 
                    amount_collected = 56, ),
                amount_collected = 56
            )
        else:
            return HelloAssoApiV5ModelsTagsInternalTagModel(
        )
        """

    def testHelloAssoApiV5ModelsTagsInternalTagModel(self):
        """Test HelloAssoApiV5ModelsTagsInternalTagModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
