# coding: utf-8

"""
    HelloAsso API

    HelloAsso Open Api specification

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.hello_asso_api_v5_models_api_notifications_api_notification_type import HelloAssoApiV5ModelsApiNotificationsApiNotificationType

class TestHelloAssoApiV5ModelsApiNotificationsApiNotificationType(unittest.TestCase):
    """HelloAssoApiV5ModelsApiNotificationsApiNotificationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHelloAssoApiV5ModelsApiNotificationsApiNotificationType(self):
        """Test HelloAssoApiV5ModelsApiNotificationsApiNotificationType"""
        # inst = HelloAssoApiV5ModelsApiNotificationsApiNotificationType()

if __name__ == '__main__':
    unittest.main()
