# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso-python.api.organization_api import OrganizationApi


class TestOrganizationApi(unittest.TestCase):
    """OrganizationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrganizationApi()

    def tearDown(self) -> None:
        pass

    def test_organizations_legal_informations_organization_slug_configuration_put(self) -> None:
        """Test case for organizations_legal_informations_organization_slug_configuration_put

        Mettre à jour la configuration des informations juridiques de l'organisation.
        """
        pass


if __name__ == '__main__':
    unittest.main()
