# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_common_models_payment_cashout_export_cashout_export_payment_operation import HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportPaymentOperation

class TestHelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportPaymentOperation(unittest.TestCase):
    """HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportPaymentOperation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportPaymentOperation(self):
        """Test HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportPaymentOperation"""
        # inst = HelloAssoApiV5CommonModelsPaymentCashoutExportCashoutExportPaymentOperation()

if __name__ == '__main__':
    unittest.main()
