# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_common_models_api_notifications_api_url_notification_model import HelloAssoApiV5CommonModelsApiNotificationsApiUrlNotificationModel

class TestHelloAssoApiV5CommonModelsApiNotificationsApiUrlNotificationModel(unittest.TestCase):
    """HelloAssoApiV5CommonModelsApiNotificationsApiUrlNotificationModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5CommonModelsApiNotificationsApiUrlNotificationModel:
        """Test HelloAssoApiV5CommonModelsApiNotificationsApiUrlNotificationModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5CommonModelsApiNotificationsApiUrlNotificationModel`
        """
        model = HelloAssoApiV5CommonModelsApiNotificationsApiUrlNotificationModel()
        if include_optional:
            return HelloAssoApiV5CommonModelsApiNotificationsApiUrlNotificationModel(
                url = '',
                api_notification_type = 'Payment',
                signature_key = ''
            )
        else:
            return HelloAssoApiV5CommonModelsApiNotificationsApiUrlNotificationModel(
        )
        """

    def testHelloAssoApiV5CommonModelsApiNotificationsApiUrlNotificationModel(self):
        """Test HelloAssoApiV5CommonModelsApiNotificationsApiUrlNotificationModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
