# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_common_models_statistics_order_light import HelloAssoApiV5CommonModelsStatisticsOrderLight

class TestHelloAssoApiV5CommonModelsStatisticsOrderLight(unittest.TestCase):
    """HelloAssoApiV5CommonModelsStatisticsOrderLight unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5CommonModelsStatisticsOrderLight:
        """Test HelloAssoApiV5CommonModelsStatisticsOrderLight
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5CommonModelsStatisticsOrderLight`
        """
        model = HelloAssoApiV5CommonModelsStatisticsOrderLight()
        if include_optional:
            return HelloAssoApiV5CommonModelsStatisticsOrderLight(
                id = 56,
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                form_slug = '',
                form_type = 'CrowdFunding',
                organization_name = '',
                organization_slug = '',
                organization_type = 'Association1901Rig',
                organization_is_under_coluche_law = True,
                checkout_intent_id = 56,
                meta = helloasso_python.models.hello_asso/api/v5/common/models/common/meta_model.HelloAsso.Api.V5.Common.Models.Common.MetaModel(
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    author_email = '', 
                    expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return HelloAssoApiV5CommonModelsStatisticsOrderLight(
        )
        """

    def testHelloAssoApiV5CommonModelsStatisticsOrderLight(self):
        """Test HelloAssoApiV5CommonModelsStatisticsOrderLight"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
