# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_models_enums_payment_type import HelloAssoApiV5ModelsEnumsPaymentType

class TestHelloAssoApiV5ModelsEnumsPaymentType(unittest.TestCase):
    """HelloAssoApiV5ModelsEnumsPaymentType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHelloAssoApiV5ModelsEnumsPaymentType(self):
        """Test HelloAssoApiV5ModelsEnumsPaymentType"""
        # inst = HelloAssoApiV5ModelsEnumsPaymentType()

if __name__ == '__main__':
    unittest.main()
