# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_common_models_forms_tier_stats_model import HelloAssoApiV5CommonModelsFormsTierStatsModel

class TestHelloAssoApiV5CommonModelsFormsTierStatsModel(unittest.TestCase):
    """HelloAssoApiV5CommonModelsFormsTierStatsModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5CommonModelsFormsTierStatsModel:
        """Test HelloAssoApiV5CommonModelsFormsTierStatsModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5CommonModelsFormsTierStatsModel`
        """
        model = HelloAssoApiV5CommonModelsFormsTierStatsModel()
        if include_optional:
            return HelloAssoApiV5CommonModelsFormsTierStatsModel(
                id = 56,
                label = '',
                description = '',
                entries_taken = 56,
                max_entries = 56,
                price = 56,
                min_amount = 56,
                price_category = 'Fixed',
                tier_type = 'Donation',
                is_enabled = True
            )
        else:
            return HelloAssoApiV5CommonModelsFormsTierStatsModel(
        )
        """

    def testHelloAssoApiV5CommonModelsFormsTierStatsModel(self):
        """Test HelloAssoApiV5CommonModelsFormsTierStatsModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
