# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_models_forms_custom_field_public_model import HelloAssoApiV5ModelsFormsCustomFieldPublicModel

class TestHelloAssoApiV5ModelsFormsCustomFieldPublicModel(unittest.TestCase):
    """HelloAssoApiV5ModelsFormsCustomFieldPublicModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5ModelsFormsCustomFieldPublicModel:
        """Test HelloAssoApiV5ModelsFormsCustomFieldPublicModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5ModelsFormsCustomFieldPublicModel`
        """
        model = HelloAssoApiV5ModelsFormsCustomFieldPublicModel()
        if include_optional:
            return HelloAssoApiV5ModelsFormsCustomFieldPublicModel(
                id = 56,
                values = [
                    ''
                    ],
                is_required = True,
                type = 'Date',
                label = ''
            )
        else:
            return HelloAssoApiV5ModelsFormsCustomFieldPublicModel(
        )
        """

    def testHelloAssoApiV5ModelsFormsCustomFieldPublicModel(self):
        """Test HelloAssoApiV5ModelsFormsCustomFieldPublicModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
