# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_common_models_common_place_model import HelloAssoApiV5CommonModelsCommonPlaceModel

class TestHelloAssoApiV5CommonModelsCommonPlaceModel(unittest.TestCase):
    """HelloAssoApiV5CommonModelsCommonPlaceModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5CommonModelsCommonPlaceModel:
        """Test HelloAssoApiV5CommonModelsCommonPlaceModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5CommonModelsCommonPlaceModel`
        """
        model = HelloAssoApiV5CommonModelsCommonPlaceModel()
        if include_optional:
            return HelloAssoApiV5CommonModelsCommonPlaceModel(
                address = '',
                name = '',
                city = '',
                zip_code = '',
                country = '012',
                geo_location = helloasso_python.models.hello_asso/models/shared/geo_location.HelloAsso.Models.Shared.GeoLocation(
                    latitude = 1.337, 
                    longitude = 1.337, )
            )
        else:
            return HelloAssoApiV5CommonModelsCommonPlaceModel(
        )
        """

    def testHelloAssoApiV5CommonModelsCommonPlaceModel(self):
        """Test HelloAssoApiV5CommonModelsCommonPlaceModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
