# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_models_partners_partner_public_model import HelloAssoApiV5ModelsPartnersPartnerPublicModel

class TestHelloAssoApiV5ModelsPartnersPartnerPublicModel(unittest.TestCase):
    """HelloAssoApiV5ModelsPartnersPartnerPublicModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5ModelsPartnersPartnerPublicModel:
        """Test HelloAssoApiV5ModelsPartnersPartnerPublicModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5ModelsPartnersPartnerPublicModel`
        """
        model = HelloAssoApiV5ModelsPartnersPartnerPublicModel()
        if include_optional:
            return HelloAssoApiV5ModelsPartnersPartnerPublicModel(
                name = '',
                display_name = '',
                description = '',
                url = '',
                logo = '',
                logo_rectangle = '',
                api_client = helloasso_python.models.hello_asso/api/v5/models/accounts/clients/api_client_model.HelloAsso.Api.V5.Models.Accounts.Clients.ApiClientModel(
                    id = '', 
                    secret = '', 
                    partner_name = '', 
                    privileges = [
                        ''
                        ], 
                    domain = '', ),
                url_notification_list = [
                    helloasso_python.models.hello_asso/api/v5/models/api_notifications/api_url_notification_model.HelloAsso.Api.V5.Models.ApiNotifications.ApiUrlNotificationModel(
                        url = '', 
                        api_notification_type = 'Payment', 
                        signature_key = '', )
                    ],
                partner_statistics = helloasso_python.models.hello_asso/api/v5/models/partner_statistics_model.HelloAsso.Api.V5.Models.PartnerStatisticsModel(
                    linked_organizations_count = 56, 
                    linked_organizations_collected_amount = 56, 
                    checkout_collected_amount = 56, 
                    organizations_using_checkout = 56, 
                    available_organizations_access_token_count = 56, )
            )
        else:
            return HelloAssoApiV5ModelsPartnersPartnerPublicModel(
        )
        """

    def testHelloAssoApiV5ModelsPartnersPartnerPublicModel(self):
        """Test HelloAssoApiV5ModelsPartnersPartnerPublicModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
