# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_models_accounts_organization_legal_informations_organization_legal_information_configuration import HelloAssoModelsAccountsOrganizationLegalInformationsOrganizationLegalInformationConfiguration

class TestHelloAssoModelsAccountsOrganizationLegalInformationsOrganizationLegalInformationConfiguration(unittest.TestCase):
    """HelloAssoModelsAccountsOrganizationLegalInformationsOrganizationLegalInformationConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoModelsAccountsOrganizationLegalInformationsOrganizationLegalInformationConfiguration:
        """Test HelloAssoModelsAccountsOrganizationLegalInformationsOrganizationLegalInformationConfiguration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoModelsAccountsOrganizationLegalInformationsOrganizationLegalInformationConfiguration`
        """
        model = HelloAssoModelsAccountsOrganizationLegalInformationsOrganizationLegalInformationConfiguration()
        if include_optional:
            return HelloAssoModelsAccountsOrganizationLegalInformationsOrganizationLegalInformationConfiguration(
                legal_structure_id = 56,
                is_hello_asso_fiscal_receipt_transmitter = True,
                is_coluche_law_enabled = True,
                is_ifi_enabled = True
            )
        else:
            return HelloAssoModelsAccountsOrganizationLegalInformationsOrganizationLegalInformationConfiguration(
        )
        """

    def testHelloAssoModelsAccountsOrganizationLegalInformationsOrganizationLegalInformationConfiguration(self):
        """Test HelloAssoModelsAccountsOrganizationLegalInformationsOrganizationLegalInformationConfiguration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
