# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_common_models_statistics_order_item import HelloAssoApiV5CommonModelsStatisticsOrderItem

class TestHelloAssoApiV5CommonModelsStatisticsOrderItem(unittest.TestCase):
    """HelloAssoApiV5CommonModelsStatisticsOrderItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5CommonModelsStatisticsOrderItem:
        """Test HelloAssoApiV5CommonModelsStatisticsOrderItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5CommonModelsStatisticsOrderItem`
        """
        model = HelloAssoApiV5CommonModelsStatisticsOrderItem()
        if include_optional:
            return HelloAssoApiV5CommonModelsStatisticsOrderItem(
                payments = [
                    helloasso_python.models.hello_asso/api/v5/common/models/statistics/share_payment.HelloAsso.Api.V5.Common.Models.Statistics.SharePayment(
                        id = 56, 
                        share_amount = 56, )
                    ],
                name = '',
                user = helloasso_python.models.hello_asso/api/v5/common/models/statistics/user.HelloAsso.Api.V5.Common.Models.Statistics.User(
                    first_name = '', 
                    last_name = '', ),
                price_category = 'Fixed',
                min_amount = 56,
                discount = helloasso_python.models.hello_asso/api/v5/common/models/statistics/item_discount.HelloAsso.Api.V5.Common.Models.Statistics.ItemDiscount(
                    code = '', 
                    amount = 56, ),
                custom_fields = [
                    helloasso_python.models.hello_asso/api/v5/common/models/statistics/item_custom_field.HelloAsso.Api.V5.Common.Models.Statistics.ItemCustomField(
                        id = 56, 
                        name = '', 
                        type = 'Date', 
                        answer = '', )
                    ],
                options = [
                    helloasso_python.models.hello_asso/api/v5/common/models/statistics/item_option.HelloAsso.Api.V5.Common.Models.Statistics.ItemOption(
                        name = '', 
                        amount = 56, 
                        price_category = 'Fixed', 
                        is_required = True, 
                        custom_fields = [
                            helloasso_python.models.hello_asso/api/v5/common/models/statistics/item_custom_field.HelloAsso.Api.V5.Common.Models.Statistics.ItemCustomField(
                                id = 56, 
                                name = '', 
                                type = 'Date', 
                                answer = '', )
                            ], 
                        option_id = 56, )
                    ],
                ticket_url = '',
                qr_code = '',
                membership_card_url = '',
                day_of_levy = 56,
                tier_description = '',
                tier_id = 56,
                comment = '',
                id = 56,
                amount = 56,
                type = 'Donation',
                initial_amount = 56,
                state = 'Waiting'
            )
        else:
            return HelloAssoApiV5CommonModelsStatisticsOrderItem(
        )
        """

    def testHelloAssoApiV5CommonModelsStatisticsOrderItem(self):
        """Test HelloAssoApiV5CommonModelsStatisticsOrderItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
