# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_common_models_enums_sort_order import HelloAssoApiV5CommonModelsEnumsSortOrder

class TestHelloAssoApiV5CommonModelsEnumsSortOrder(unittest.TestCase):
    """HelloAssoApiV5CommonModelsEnumsSortOrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHelloAssoApiV5CommonModelsEnumsSortOrder(self):
        """Test HelloAssoApiV5CommonModelsEnumsSortOrder"""
        # inst = HelloAssoApiV5CommonModelsEnumsSortOrder()

if __name__ == '__main__':
    unittest.main()
