# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_models_enums_payment_cash_out_state import HelloAssoApiV5ModelsEnumsPaymentCashOutState

class TestHelloAssoApiV5ModelsEnumsPaymentCashOutState(unittest.TestCase):
    """HelloAssoApiV5ModelsEnumsPaymentCashOutState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHelloAssoApiV5ModelsEnumsPaymentCashOutState(self):
        """Test HelloAssoApiV5ModelsEnumsPaymentCashOutState"""
        # inst = HelloAssoApiV5ModelsEnumsPaymentCashOutState()

if __name__ == '__main__':
    unittest.main()
