# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_common_models_statistics_user import HelloAssoApiV5CommonModelsStatisticsUser

class TestHelloAssoApiV5CommonModelsStatisticsUser(unittest.TestCase):
    """HelloAssoApiV5CommonModelsStatisticsUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5CommonModelsStatisticsUser:
        """Test HelloAssoApiV5CommonModelsStatisticsUser
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5CommonModelsStatisticsUser`
        """
        model = HelloAssoApiV5CommonModelsStatisticsUser()
        if include_optional:
            return HelloAssoApiV5CommonModelsStatisticsUser(
                first_name = '',
                last_name = ''
            )
        else:
            return HelloAssoApiV5CommonModelsStatisticsUser(
        )
        """

    def testHelloAssoApiV5CommonModelsStatisticsUser(self):
        """Test HelloAssoApiV5CommonModelsStatisticsUser"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
