# coding: utf-8

"""
    HelloAsso API

    HelloAsso Open Api specification

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.hello_asso_api_v5_models_enums_organization_type import HelloAssoApiV5ModelsEnumsOrganizationType

class TestHelloAssoApiV5ModelsEnumsOrganizationType(unittest.TestCase):
    """HelloAssoApiV5ModelsEnumsOrganizationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHelloAssoApiV5ModelsEnumsOrganizationType(self):
        """Test HelloAssoApiV5ModelsEnumsOrganizationType"""
        # inst = HelloAssoApiV5ModelsEnumsOrganizationType()

if __name__ == '__main__':
    unittest.main()
