# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_common_models_carts_checkout_term import HelloAssoApiV5CommonModelsCartsCheckoutTerm

class TestHelloAssoApiV5CommonModelsCartsCheckoutTerm(unittest.TestCase):
    """HelloAssoApiV5CommonModelsCartsCheckoutTerm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5CommonModelsCartsCheckoutTerm:
        """Test HelloAssoApiV5CommonModelsCartsCheckoutTerm
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5CommonModelsCartsCheckoutTerm`
        """
        model = HelloAssoApiV5CommonModelsCartsCheckoutTerm()
        if include_optional:
            return HelloAssoApiV5CommonModelsCartsCheckoutTerm(
                amount = 56,
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return HelloAssoApiV5CommonModelsCartsCheckoutTerm(
                amount = 56,
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testHelloAssoApiV5CommonModelsCartsCheckoutTerm(self):
        """Test HelloAssoApiV5CommonModelsCartsCheckoutTerm"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
