# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_models_enums_sort_order import HelloAssoApiV5ModelsEnumsSortOrder

class TestHelloAssoApiV5ModelsEnumsSortOrder(unittest.TestCase):
    """HelloAssoApiV5ModelsEnumsSortOrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHelloAssoApiV5ModelsEnumsSortOrder(self):
        """Test HelloAssoApiV5ModelsEnumsSortOrder"""
        # inst = HelloAssoApiV5ModelsEnumsSortOrder()

if __name__ == '__main__':
    unittest.main()
