# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_models_carts_init_checkout_response import HelloAssoApiV5ModelsCartsInitCheckoutResponse

class TestHelloAssoApiV5ModelsCartsInitCheckoutResponse(unittest.TestCase):
    """HelloAssoApiV5ModelsCartsInitCheckoutResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5ModelsCartsInitCheckoutResponse:
        """Test HelloAssoApiV5ModelsCartsInitCheckoutResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5ModelsCartsInitCheckoutResponse`
        """
        model = HelloAssoApiV5ModelsCartsInitCheckoutResponse()
        if include_optional:
            return HelloAssoApiV5ModelsCartsInitCheckoutResponse(
                id = 56,
                redirect_url = ''
            )
        else:
            return HelloAssoApiV5ModelsCartsInitCheckoutResponse(
        )
        """

    def testHelloAssoApiV5ModelsCartsInitCheckoutResponse(self):
        """Test HelloAssoApiV5ModelsCartsInitCheckoutResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
