# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_common_models_enums_sort_field import HelloAssoApiV5CommonModelsEnumsSortField

class TestHelloAssoApiV5CommonModelsEnumsSortField(unittest.TestCase):
    """HelloAssoApiV5CommonModelsEnumsSortField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHelloAssoApiV5CommonModelsEnumsSortField(self):
        """Test HelloAssoApiV5CommonModelsEnumsSortField"""
        # inst = HelloAssoApiV5CommonModelsEnumsSortField()

if __name__ == '__main__':
    unittest.main()
