# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_models_enums_field_type import HelloAssoApiV5ModelsEnumsFieldType

class TestHelloAssoApiV5ModelsEnumsFieldType(unittest.TestCase):
    """HelloAssoApiV5ModelsEnumsFieldType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHelloAssoApiV5ModelsEnumsFieldType(self):
        """Test HelloAssoApiV5ModelsEnumsFieldType"""
        # inst = HelloAssoApiV5ModelsEnumsFieldType()

if __name__ == '__main__':
    unittest.main()
