# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_models_organizations_organization_public_configurations_request import HelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationsRequest

class TestHelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationsRequest(unittest.TestCase):
    """HelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationsRequest:
        """Test HelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationsRequest`
        """
        model = HelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationsRequest()
        if include_optional:
            return HelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationsRequest(
                configurations = [
                    helloasso_python.models.hello_asso/api/v5/models/organizations/organization_public_configuration_model.HelloAsso.Api.V5.Models.Organizations.OrganizationPublicConfigurationModel(
                        name = 'DonationSepaEnabled', 
                        value = null, )
                    ]
            )
        else:
            return HelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationsRequest(
        )
        """

    def testHelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationsRequest(self):
        """Test HelloAssoApiV5ModelsOrganizationsOrganizationPublicConfigurationsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
