# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_models_partner_statistics_model import HelloAssoApiV5ModelsPartnerStatisticsModel

class TestHelloAssoApiV5ModelsPartnerStatisticsModel(unittest.TestCase):
    """HelloAssoApiV5ModelsPartnerStatisticsModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5ModelsPartnerStatisticsModel:
        """Test HelloAssoApiV5ModelsPartnerStatisticsModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5ModelsPartnerStatisticsModel`
        """
        model = HelloAssoApiV5ModelsPartnerStatisticsModel()
        if include_optional:
            return HelloAssoApiV5ModelsPartnerStatisticsModel(
                linked_organizations_count = 56,
                linked_organizations_collected_amount = 56,
                checkout_collected_amount = 56,
                organizations_using_checkout = 56,
                available_organizations_access_token_count = 56
            )
        else:
            return HelloAssoApiV5ModelsPartnerStatisticsModel(
        )
        """

    def testHelloAssoApiV5ModelsPartnerStatisticsModel(self):
        """Test HelloAssoApiV5ModelsPartnerStatisticsModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
