# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_common_models_common_meta_model import HelloAssoApiV5CommonModelsCommonMetaModel

class TestHelloAssoApiV5CommonModelsCommonMetaModel(unittest.TestCase):
    """HelloAssoApiV5CommonModelsCommonMetaModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5CommonModelsCommonMetaModel:
        """Test HelloAssoApiV5CommonModelsCommonMetaModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5CommonModelsCommonMetaModel`
        """
        model = HelloAssoApiV5CommonModelsCommonMetaModel()
        if include_optional:
            return HelloAssoApiV5CommonModelsCommonMetaModel(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                author_email = '',
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return HelloAssoApiV5CommonModelsCommonMetaModel(
        )
        """

    def testHelloAssoApiV5CommonModelsCommonMetaModel(self):
        """Test HelloAssoApiV5CommonModelsCommonMetaModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
