# coding: utf-8

"""
    HelloAsso API

    HelloAsso Open Api specification

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.hello_asso_models_compliance_v2_common_address_address_model_snapshot import HelloAssoModelsComplianceV2CommonAddressAddressModelSnapshot

class TestHelloAssoModelsComplianceV2CommonAddressAddressModelSnapshot(unittest.TestCase):
    """HelloAssoModelsComplianceV2CommonAddressAddressModelSnapshot unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoModelsComplianceV2CommonAddressAddressModelSnapshot:
        """Test HelloAssoModelsComplianceV2CommonAddressAddressModelSnapshot
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoModelsComplianceV2CommonAddressAddressModelSnapshot`
        """
        model = HelloAssoModelsComplianceV2CommonAddressAddressModelSnapshot()
        if include_optional:
            return HelloAssoModelsComplianceV2CommonAddressAddressModelSnapshot(
                line = '',
                city = '',
                zip_code = '',
                country = '',
                iso_country = 56
            )
        else:
            return HelloAssoModelsComplianceV2CommonAddressAddressModelSnapshot(
        )
        """

    def testHelloAssoModelsComplianceV2CommonAddressAddressModelSnapshot(self):
        """Test HelloAssoModelsComplianceV2CommonAddressAddressModelSnapshot"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
