# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.api.organization_public_configurations_api import OrganizationPublicConfigurationsApi


class TestOrganizationPublicConfigurationsApi(unittest.TestCase):
    """OrganizationPublicConfigurationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrganizationPublicConfigurationsApi()

    def tearDown(self) -> None:
        pass

    def test_organizations_organization_slug_configurations_get(self) -> None:
        """Test case for organizations_organization_slug_configurations_get

        """
        pass

    def test_organizations_organization_slug_configurations_put(self) -> None:
        """Test case for organizations_organization_slug_configurations_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
