# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_models_api_notifications_post_api_url_notification_body import HelloAssoApiV5ModelsApiNotificationsPostApiUrlNotificationBody

class TestHelloAssoApiV5ModelsApiNotificationsPostApiUrlNotificationBody(unittest.TestCase):
    """HelloAssoApiV5ModelsApiNotificationsPostApiUrlNotificationBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5ModelsApiNotificationsPostApiUrlNotificationBody:
        """Test HelloAssoApiV5ModelsApiNotificationsPostApiUrlNotificationBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5ModelsApiNotificationsPostApiUrlNotificationBody`
        """
        model = HelloAssoApiV5ModelsApiNotificationsPostApiUrlNotificationBody()
        if include_optional:
            return HelloAssoApiV5ModelsApiNotificationsPostApiUrlNotificationBody(
                url = '0',
                notification_type = 'Payment'
            )
        else:
            return HelloAssoApiV5ModelsApiNotificationsPostApiUrlNotificationBody(
                url = '0',
        )
        """

    def testHelloAssoApiV5ModelsApiNotificationsPostApiUrlNotificationBody(self):
        """Test HelloAssoApiV5ModelsApiNotificationsPostApiUrlNotificationBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
