# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.api.partenaires_api import PartenairesApi


class TestPartenairesApi(unittest.TestCase):
    """PartenairesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PartenairesApi()

    def tearDown(self) -> None:
        pass

    def test_partners_me_api_clients_put(self) -> None:
        """Test case for partners_me_api_clients_put

        Mise à jour du domaine
        """
        pass

    def test_partners_me_api_notifications_delete(self) -> None:
        """Test case for partners_me_api_notifications_delete

        Suppression de l'URL de notification principale
        """
        pass

    def test_partners_me_api_notifications_organizations_organization_slug_delete(self) -> None:
        """Test case for partners_me_api_notifications_organizations_organization_slug_delete

        Suppression d'une URL de notification liée à une organisation
        """
        pass

    def test_partners_me_api_notifications_organizations_organization_slug_put(self) -> None:
        """Test case for partners_me_api_notifications_organizations_organization_slug_put

        Mise à jour d'une URL de notification liée à une organisation
        """
        pass

    def test_partners_me_api_notifications_put(self) -> None:
        """Test case for partners_me_api_notifications_put

        Mise à jour de l'URL de notification principale
        """
        pass

    def test_partners_me_get(self) -> None:
        """Test case for partners_me_get

        Récupération des informations
        """
        pass

    def test_partners_me_organizations_get(self) -> None:
        """Test case for partners_me_organizations_get

        Obtenir toutes les organisations
        """
        pass


if __name__ == '__main__':
    unittest.main()
