# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_common_models_forms_extra_option_public_model import HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel

class TestHelloAssoApiV5CommonModelsFormsExtraOptionPublicModel(unittest.TestCase):
    """HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel:
        """Test HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel`
        """
        model = HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel()
        if include_optional:
            return HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel(
                custom_fields = [
                    helloasso_python.models.hello_asso/api/v5/common/models/forms/custom_field_public_model.HelloAsso.Api.V5.Common.Models.Forms.CustomFieldPublicModel(
                        id = 56, 
                        values = [
                            ''
                            ], 
                        is_required = True, 
                        type = 'Date', 
                        label = '', )
                    ],
                id = 56,
                price = 56,
                vat_rate = 1.337,
                label = '',
                description = '',
                is_required = True
            )
        else:
            return HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel(
        )
        """

    def testHelloAssoApiV5CommonModelsFormsExtraOptionPublicModel(self):
        """Test HelloAssoApiV5CommonModelsFormsExtraOptionPublicModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
