# coding: utf-8

"""
    HelloAsso API

    HelloAsso Open Api specification

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.organization_legal_informations_api import OrganizationLegalInformationsApi


class TestOrganizationLegalInformationsApi(unittest.TestCase):
    """OrganizationLegalInformationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrganizationLegalInformationsApi()

    def tearDown(self) -> None:
        pass

    def test_organizations_legal_informations_organization_slug_configuration_put(self) -> None:
        """Test case for organizations_legal_informations_organization_slug_configuration_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
