# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_common_models_organizations_organization_basic_model import HelloAssoApiV5CommonModelsOrganizationsOrganizationBasicModel

class TestHelloAssoApiV5CommonModelsOrganizationsOrganizationBasicModel(unittest.TestCase):
    """HelloAssoApiV5CommonModelsOrganizationsOrganizationBasicModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5CommonModelsOrganizationsOrganizationBasicModel:
        """Test HelloAssoApiV5CommonModelsOrganizationsOrganizationBasicModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5CommonModelsOrganizationsOrganizationBasicModel`
        """
        model = HelloAssoApiV5CommonModelsOrganizationsOrganizationBasicModel()
        if include_optional:
            return HelloAssoApiV5CommonModelsOrganizationsOrganizationBasicModel(
                url = '',
                organization_slug = ''
            )
        else:
            return HelloAssoApiV5CommonModelsOrganizationsOrganizationBasicModel(
        )
        """

    def testHelloAssoApiV5CommonModelsOrganizationsOrganizationBasicModel(self):
        """Test HelloAssoApiV5CommonModelsOrganizationsOrganizationBasicModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
