# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.api.reus_fiscaux_api import ReusFiscauxApi


class TestReusFiscauxApi(unittest.TestCase):
    """ReusFiscauxApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ReusFiscauxApi()

    def tearDown(self) -> None:
        pass

    def test_organizations_organization_slug_tax_receipt_configuration_get(self) -> None:
        """Test case for organizations_organization_slug_tax_receipt_configuration_get

        Obtenir la configuration des reçus fiscaux
        """
        pass

    def test_organizations_organization_slug_tax_receipt_configuration_put(self) -> None:
        """Test case for organizations_organization_slug_tax_receipt_configuration_put

        Mettre à jour la configuration des reçus fiscaux
        """
        pass

    def test_organizations_organization_slug_tax_receipt_fiscal_receipt_transmitter_put(self) -> None:
        """Test case for organizations_organization_slug_tax_receipt_fiscal_receipt_transmitter_put

        Mettre à jour l'émetteur des reçus fiscaux
        """
        pass

    def test_organizations_organization_slug_tax_receipt_preview_post(self) -> None:
        """Test case for organizations_organization_slug_tax_receipt_preview_post

        Prévisualiser les reçus fiscaux
        """
        pass


if __name__ == '__main__':
    unittest.main()
