# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from helloasso_python.models.hello_asso_api_v5_models_accounts_clients_public_put_api_client_request import HelloAssoApiV5ModelsAccountsClientsPublicPutApiClientRequest

class TestHelloAssoApiV5ModelsAccountsClientsPublicPutApiClientRequest(unittest.TestCase):
    """HelloAssoApiV5ModelsAccountsClientsPublicPutApiClientRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoApiV5ModelsAccountsClientsPublicPutApiClientRequest:
        """Test HelloAssoApiV5ModelsAccountsClientsPublicPutApiClientRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoApiV5ModelsAccountsClientsPublicPutApiClientRequest`
        """
        model = HelloAssoApiV5ModelsAccountsClientsPublicPutApiClientRequest()
        if include_optional:
            return HelloAssoApiV5ModelsAccountsClientsPublicPutApiClientRequest(
                domain = ''
            )
        else:
            return HelloAssoApiV5ModelsAccountsClientsPublicPutApiClientRequest(
        )
        """

    def testHelloAssoApiV5ModelsAccountsClientsPublicPutApiClientRequest(self):
        """Test HelloAssoApiV5ModelsAccountsClientsPublicPutApiClientRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
