# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class HelloAssoModelsAccountsOrganizationLegalInformationsTaxInformationText(BaseModel):
    """
    HelloAssoModelsAccountsOrganizationLegalInformationsTaxInformationText
    """ # noqa: E501
    is_coluche_law_enabled: Optional[StrictBool] = Field(default=None, alias="isColucheLawEnabled")
    is_ifi_enabled: Optional[StrictBool] = Field(default=None, alias="isIfiEnabled")
    individual_text: Optional[StrictStr] = Field(default=None, alias="individualText")
    company_text: Optional[StrictStr] = Field(default=None, alias="companyText")
    __properties: ClassVar[List[str]] = ["isColucheLawEnabled", "isIfiEnabled", "individualText", "companyText"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HelloAssoModelsAccountsOrganizationLegalInformationsTaxInformationText from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if individual_text (nullable) is None
        # and model_fields_set contains the field
        if self.individual_text is None and "individual_text" in self.model_fields_set:
            _dict['individualText'] = None

        # set to None if company_text (nullable) is None
        # and model_fields_set contains the field
        if self.company_text is None and "company_text" in self.model_fields_set:
            _dict['companyText'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HelloAssoModelsAccountsOrganizationLegalInformationsTaxInformationText from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "isColucheLawEnabled": obj.get("isColucheLawEnabled"),
            "isIfiEnabled": obj.get("isIfiEnabled"),
            "individualText": obj.get("individualText"),
            "companyText": obj.get("companyText")
        })
        return _obj


