# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class HelloAssoApiV5ModelsEnumsOrganizationType(str, Enum):
    """
    HelloAssoApiV5ModelsEnumsOrganizationType
    """

    """
    allowed enum values
    """
    ASSOCIATION1901RIG = 'Association1901Rig'
    ASSOCIATION1901RUP = 'Association1901Rup'
    ASSOCIATION1901 = 'Association1901'
    FONDATIONRUP = 'FondationRup'
    FONDDOTATION = 'FondDotation'
    FONDATIONSOUSEGIDE = 'FondationSousEgide'
    FONDATIONSCIENTIFIQUE = 'FondationScientifique'
    FONDATIONPARTENARIALE = 'FondationPartenariale'
    FONDATIONUNIVERSITAIRE = 'FondationUniversitaire'
    FONDATIONHOSPITALIERE = 'FondationHospitaliere'
    ASSOCIATION1905 = 'Association1905'
    ASSOCIATION1905RUP = 'Association1905Rup'
    ENTREPRISE = 'Entreprise'
    COOPERATIVE = 'Cooperative'
    ETABLISSEMENT = 'Etablissement'
    ASSOCIATION1908 = 'Association1908'
    ASSOCIATION1908RIG = 'Association1908Rig'
    ASSOCIATION1908RUP = 'Association1908Rup'
    ASSOCIATIONMILITAIRE = 'AssociationMilitaire'
    ASSOCIATIONPROPRIETAIRE = 'AssociationProprietaire'
    COLLECTIVITÉS = 'Collectivités'
    COMITEENTREPRISE = 'ComiteEntreprise'
    CSE = 'CSE'
    FABRIQUEEGLISE = 'FabriqueEglise'
    FONDSPERENITE = 'FondsPerenite'
    GIE = 'GIE'
    GIP = 'GIP'
    MENSECURIALE = 'MenseCuriale'
    SCIC = 'SCIC'
    SCOP = 'SCOP'
    AUTRES = 'Autres'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of HelloAssoApiV5ModelsEnumsOrganizationType from a JSON string"""
        return cls(json.loads(json_str))


