# coding: utf-8

"""
    HelloAsso API

    HelloAsso auto-generated SDK

    The version of the OpenAPI document: public
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class HelloAssoApiV5ModelsEnumsPaymentProviderType(str, Enum):
    """
    The payment provider type.
    """

    """
    allowed enum values
    """
    LEMONWAY = 'Lemonway'
    STRIPE = 'Stripe'
    STRIPEV2 = 'StripeV2'
    HAPAY = 'HaPay'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of HelloAssoApiV5ModelsEnumsPaymentProviderType from a JSON string"""
        return cls(json.loads(json_str))


